### ISSUE TITLE
Favorites command

### ISSUE THREAD

**Issue by kodaman2** [mickaobrien/vim-stackoverflow#4]
Awesome plugin, I would like to add some features to this plugin if you think is a good idea to have it in this plug in. If not I can make another solo plugin but I think Favorites is such of good part of SO.

New Command:
- StackFavorites 'vim' {returns user favorites with 'vim' in it}
- StackFavorites {returns latest 50 favorites} (Configurable)

Optional:
When browsing questions with StackOverflow command, ability to save a question to favorites with a letter command much like o opens and closes a question.

Let me know if you are interested and I can start working on it.

**Comment by mickaobrien** [comment]
@kodaman2 Hey, thanks for getting in touch — sorry for not getting back to you sooner! That feature sounds interesting, it's not something I use so I'm not sure how it should work but if you're happy to add it, work away.

**Comment by kodaman2** [comment]
Hey no worries. I'll see what I can come up with, I think the hardest part might be the oath authentication, but I am sure I can figure it out. The rest is trivial api get requests. I'll close issue, and send initial PR when I get it working.
